--- 
- 
  become: true
  hosts: control
  tasks: 
    - 
      name: "install nginx"
      yum: "name={{item}} state=present"
      with_items:
         - epel-release
         - nginx
    - 
      name: "nginx service start"
      systemd: "name={{item}} state=restarted enabled=yes"
      with_items:
          - nginx
