--- 
- 
  become: true
  hosts: control
  tasks: 
    - 
      name: "install nginx"
      yum: "name=epel-release state=present"
    - 
      name: "install nginx"
      yum: "name=nginx state=present"
    - 
      name: "nginx service start"
      systemd: "name=nginx state=started enabled=yes"
